_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.9.20
        t:
            "1":
                - 1
                - 50
                - 55
            "2":
                - 1
                - 50
                - 55
            "3":
                - 2
                - 13
                - 16
                - 23
                - 35
                - 55
            "4": 3.9.20
            "5": 0.18.7
            "8":
                - 5
            "12": 0.18.7
            "13": darwin-arm64
bc_algo:
    value:
        batch_size: 64
        epochs: 100
        training_interval: 1000000
compute:
    value:
        n_cpu_workers: 8
        n_gpu_workers: 1
env:
    value:
        episode_length: 100
        example_name: map2
        include_history: false
log_folder:
    value: toy_its/train_logs/
logging:
    value:
        log_freq: 300
        model_save_freq: 1000000
        run_name: 2024-12-02-160846_map=map2_rl=ppo-epochs=10-eplen=100_s=9_nt=None
        run_path: /Users/yujinkim/Desktop/its_minigrid/toy_its/train_logs/2024-12-02-160846_map=map2_rl=ppo-epochs=10-eplen=100_s=9_nt=None
        video_save_freq: 1000000
        wandb_mode: online
        wandb_project: toy_its
        wandb_tags: []
model_base_path:
    value: null
model_checkpoint:
    value: null
rl_algo:
    value:
        batch_size: 64
        ent_coef: 0.25
        gamma: 0.99
        lr: 0.00025
        "n": null
        n_epochs: 10
        name: ppo
        total_timesteps: 5000000
        use_relative_rewards: false
        vf_coef: 1
run_notes:
    value: null
seed:
    value: 9
